'use client'
import {Inter} from 'next/font/google'
import {usePathname, useSearchParams} from 'next/navigation'
import {Suspense, useEffect, useState} from 'react'
import Loader from './Loader'

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  //const [content, setContent] = useState('')
  const pathname = usePathname()
  const searchParams = useSearchParams()
  useEffect(() => {
    //setContent(children)
    console.log('children is: ', children)
  }, [pathname, searchParams])
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Suspense fallback={<Loader />}>{children}</Suspense>
      </body>
    </html>
  )
}
